name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Authenticate
      run: dotnet nuget add source https://packages.infragistics.com/nuget/licensed/ -n Infragistics -u api -p "${NUGET_AUTH_TOKEN#api:}" --store-password-in-clear-text
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Upload Build Artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: build_output/wwwroot

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1